### ISSUE TITLE
Proposal: Rename Repo

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs-vagrant#3]
This repo should be named vagrant-donejs to make it not collid with the reserved donejs-* namespace wich is reserved for donejs-* generators.

- is related to: https://github.com/donejs/donejs/issues/998
- this is blocking for https://github.com/donejs/donejs-vagrant/issues/4

**Comment by pYr0x** [comment]
i am ok with that.

**Comment by frank-dspeed** [comment]
@pYr0x then some one with access needs to do that i have nothing :)

**Comment by pYr0x** [comment]
renamed
